<?php 
	use Zend\Registry;
?>
<?= $this->plugin('doctype'); ?>

<html>
<head>
<?php 
    echo $this->plugin('headTitle'); 
    echo $this->plugin('headMeta'); 
    echo $this->plugin('headLink'); 
    echo $this->plugin('headScript'); 
?> 
<link href="/favicon.ico" type="image/x-icon" rel="icon" />
<link href="/favicon.ico" type="image/x-icon" rel="shortcut icon" />
</head>
<body>

<div id="pageContainer" class="container">
	
	<noscript>Please activate Javascript to use this website!</noscript>
	
	<div class="topbar">
		<div class="fill">
			<div class="container">
				<h3><a href="/">Buggy</a></h3>
				<ul>
					<li<?php if ($this->controller == 'index') echo ' class="active"'; ?>>
						<a href="/index/index">Index</a>
					</li>
					<li<?php if ($this->controller == 'zyx') echo ' class="active"'; ?>>
						<a href="/abc/zyx">Zyx</a>
					</li>
					<li<?php if ($this->controller == 'yxz') echo ' class="active"'; ?>>
						<a href="/abc/yxz">Yxz</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	<?php echo $this->raw('content'); ?>

	<footer>
    	<p class="row">
    		<span class="span14 columns">
    			&copy; <b>we</b>{src} Michael Scholl &amp; Leander Damme
    		</span>
    		<?php if (Registry::isRegistered('user')) : ?>
    		<span class="span2 columns tright">
    			<a class="btn small" href="<?php
        		    echo $this->url(array(
        		        'module' => 'auth',
        		        'controller' => 'auth', 
        		    	'action' => 'logout'
        		    ), 'auth', true);
    		    ?>">Logout</a>
    		</span>
    		<?php endif; ?>
    	</p>
	</footer>

</div>

</body>
</html>
