
<strong>Module:</strong>        Application &raquo; 
<strong>Controller:</strong>    Index &raquo; 
<strong>Action:</strong>        index
    <?php $this->markdown()->start(); ?>
    Hello, **this** is _markdown_!
    ====================

A Second Level Header
---------------------

Now is the time for all good men to come to
the aid of their country. This is just a
regular paragraph.

The quick brown fox jumped over the lazy
dog's back.

### Header 3

> This is a blockquote.
> 
> This is the second paragraph in the blockquote.
>
### This is an H2 in a blockquote
<?php $this->markdown()->end(); ?>